#cloud-config
groups:
  - debian: [root, sys]

users:
  - default
  - name: ${LINUX_USERNAME_DEVOPS_HUMAN_DEB020325}
    gecos: Developer Access Account - ${LINUX_USERNAME_DEVOPS_HUMAN_DEB020325}
    shell: /bin/bash
    primary_group: ${LINUX_USERNAME_DEVOPS_HUMAN_DEB020325}
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, docker
    lock_passwd: false
    ssh_authorized_keys:
      - ${LINUX_HUMAN_SSH_KEY_PUB_WITHPASS_DEB020325}

  - name: ${TF_VAR_LINUX_USERNAME_GHA_CICD_BOT_DEB020325}
    gecos: GitHub Actions CI/CD Bot - ${TF_VAR_LINUX_USERNAME_GHA_CICD_BOT_DEB020325}
    shell: /bin/bash
    primary_group: ${TF_VAR_LINUX_USERNAME_GHA_CICD_BOT_DEB020325}
    sudo: ALL=(ALL) NOPASSWD:/usr/bin/docker,/usr/bin/docker-compose
    groups: docker
    lock_passwd: true
    ssh_authorized_keys:
      - ${LINUX_GHACICD_BOT_SSH_KEY_PUB_NOPASS_DEB020325}

# This creates our initial user
chpasswd:
  expire: false
  users:
    - name: ${LINUX_USERNAME_DEVOPS_HUMAN_DEB020325}
      password: ${LINUX_USERPASSWORD_DEVOPS_HUMAN_DEB020325}
      type: text

package_update: true
package_upgrade: true
packages:
  - zsh
  - git
  - make
  - rsync

runcmd:
  # Update package lists before installing anything
  - sudo apt-get update
  # Install Docker using the official script
  - curl -fsSL https://get.docker.com -o get-docker.sh
  - sh get-docker.sh
  - sudo usermod -aG docker ${LINUX_USERNAME_DEVOPS_HUMAN_DEB020325}
  # Install rsync with error handling
  - sudo apt-get install -y rsync || echo "Failed to install rsync"
